### ISSUE TITLE
`gem_original_require': no such file to load -- JSON

### ISSUE THREAD

**Issue by 0x19** [tmacwill/asana-client#6]
I'm getting this error. Any thoughts about it? Tried to install json, json_pure. Gone throu steps you defined and created ./asana-client file but whatever I install, this is always as-is:

``` shell
/usr/lib/ruby/vendor_ruby/1.8/rubygems/custom_require.rb:36:in `gem_original_require': no such file to load -- JSON (LoadError)
    from /usr/lib/ruby/vendor_ruby/1.8/rubygems/custom_require.rb:36:in `require'
    from /var/lib/gems/1.8/gems/asana-client-0.0.1/lib/asana-client.rb:10
    from /usr/lib/ruby/vendor_ruby/1.8/rubygems/custom_require.rb:36:in `gem_original_require'
    from /usr/lib/ruby/vendor_ruby/1.8/rubygems/custom_require.rb:36:in `require'
    from /var/lib/gems/1.8/gems/asana-client-0.0.1/bin/asana:3
    from /usr/local/bin/asana:19:in `load'
    from /usr/local/bin/asana:19
```

Thanks!

**Comment by aaronfay** [comment]
Similar issue in ruby 1.9.1 on linux:

``` bash
/usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require': cannot load such file -- JSON (LoadError)
    from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /var/lib/gems/1.9.1/gems/asana-client-0.0.1/lib/asana-client.rb:10:in `<top (required)>'
    from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /var/lib/gems/1.9.1/gems/asana-client-0.0.1/bin/asana:3:in `<top (required)>'
    from /usr/local/bin/asana:19:in `load'
    from /usr/local/bin/asana:19:in `<main>'
```

**Comment by 0x19** [comment]
``` shell

/home/waax/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require': cannot load such file -- JSON (LoadError)
    from /home/waax/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /home/waax/.rvm/gems/ruby-1.9.3-p194/gems/asana-client-0.0.1/lib/asana-client.rb:10:in `<top (required)>'
    from /home/waax/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /home/waax/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /home/waax/.rvm/gems/ruby-1.9.3-p194/gems/asana-client-0.0.1/bin/asana:3:in `<top (required)>'
    from /home/waax/.rvm/gems/ruby-1.9.3-p194/bin/asana:19:in `load'
    from /home/waax/.rvm/gems/ruby-1.9.3-p194/bin/asana:19:in `<main>'
    from /home/waax/.rvm/gems/ruby-1.9.3-p194/bin/ruby_noexec_wrapper:14:in `eval'
    from /home/waax/.rvm/gems/ruby-1.9.3-p194/bin/ruby_noexec_wrapper:14:in `<main>'
```
